import { api } from './api'

export const livros_mock = [
  { id: 1, titulo: 'Hábitos Atômicos', autor: 'James Clear', editora: 'Alta Books', categoria: 'Desenvolvimento Pessoal', preco: 52.90, precoOriginal: 69.90, avaliacao: 4.9, avaliacoes: 2341, estoque: 45, paginas: 320, ano: 2019, isbn: '978-8550807188', idioma: 'Português', descricao: 'Uma maneira fácil e comprovada de criar bons hábitos e acabar com os maus. Este livro apresenta estratégias práticas baseadas em ciência para reformular suas rotinas e comportamentos de forma simples e eficaz.', capa: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Autoajuda' },
  { id: 2, titulo: 'Pai Rico Pai Pobre', autor: 'Robert Kiyosaki', editora: 'Alta Books', categoria: 'Negócios', preco: 44.90, precoOriginal: 59.90, avaliacao: 4.8, avaliacoes: 5120, estoque: 62, paginas: 280, ano: 1997, isbn: '978-8550801377', idioma: 'Português', descricao: 'O que os ricos ensinam a seus filhos sobre dinheiro que a classe média e os pobres não ensinam. Uma das obras mais influentes sobre educação financeira e independência econômica.', capa: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Finanças' },
  { id: 3, titulo: 'A Sutil Arte de Ligar o F*da-se', autor: 'Mark Manson', editora: 'Intrínseca', categoria: 'Desenvolvimento Pessoal', preco: 39.90, precoOriginal: 49.90, avaliacao: 4.7, avaliacoes: 3876, estoque: 38, paginas: 224, ano: 2016, isbn: '978-8551002827', idioma: 'Português', descricao: 'Uma abordagem diferente para uma vida melhor. Mark Manson argui que melhorar em tudo que fazemos é ótimo, mas o segredo é saber o que merece o nosso esforço.', capa: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Autoajuda' },
  { id: 4, titulo: 'O Homem Mais Rico da Babilônia', autor: 'George S. Clason', editora: 'Editora Ediouro', categoria: 'Negócios', preco: 29.90, precoOriginal: 39.90, avaliacao: 4.8, avaliacoes: 4201, estoque: 91, paginas: 160, ano: 1926, isbn: '978-8500018916', idioma: 'Português', descricao: 'Clássico sobre finanças pessoais apresentado através de parábolas ambientadas na Babilônia Antiga. Princípios atemporais sobre poupança, investimento e criação de riqueza.', capa: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Finanças' },
  { id: 5, titulo: 'Os Segredos da Mente Milionária', autor: 'T. Harv Eker', editora: 'Sextante', categoria: 'Negócios', preco: 34.90, precoOriginal: 44.90, avaliacao: 4.6, avaliacoes: 2987, estoque: 54, paginas: 208, ano: 2006, isbn: '978-8575423004', idioma: 'Português', descricao: 'Eker revela como a forma como você pensa sobre dinheiro determina o quanto você tem. Com exercícios práticos, este livro expande sua forma de pensar sobre riqueza.', capa: 'https://images.unsplash.com/photo-1460467820054-c87ab43e9b59?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Finanças' },
  { id: 6, titulo: '1984', autor: 'George Orwell', editora: 'Companhia das Letras', categoria: 'Ficção', preco: 38.90, precoOriginal: 49.90, avaliacao: 4.9, avaliacoes: 6543, estoque: 77, paginas: 416, ano: 1949, isbn: '978-8535914849', idioma: 'Português', descricao: 'A mais poderosa distopia já escrita, "1984" de George Orwell traz à vida uma sociedade totalitária onde o Estado controla tudo, inclusive o pensamento das pessoas.', capa: 'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Literatura' },
  { id: 7, titulo: 'Duna', autor: 'Frank Herbert', editora: 'Aleph', categoria: 'Ficção', preco: 64.90, precoOriginal: 79.90, avaliacao: 4.9, avaliacoes: 4102, estoque: 33, paginas: 720, ano: 1965, isbn: '978-8576573456', idioma: 'Português', descricao: 'O romance de ficção científica mais vendido de todos os tempos. Acompanhe Paul Atreides em uma epopeia de poder, política, religião e ecologia em um planeta deserto.', capa: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Ficção Científica' },
  { id: 8, titulo: 'O Hobbit', autor: 'J.R.R. Tolkien', editora: 'HarperCollins', categoria: 'Ficção', preco: 42.90, precoOriginal: 54.90, avaliacao: 4.9, avaliacoes: 7891, estoque: 58, paginas: 336, ano: 1937, isbn: '978-8595084742', idioma: 'Português', descricao: 'A aventura inesperada de Bilbo Bolseiro, que parte de casa para uma jornada épica com treze anões e o mago Gandalf em busca de um tesouro guardado por um dragão.', capa: 'https://images.unsplash.com/photo-1506466010722-395aa2bef877?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Fantasia' },
  { id: 9, titulo: 'O Poder da Ação', autor: 'Paulo Vieira', editora: 'Gente', categoria: 'Desenvolvimento Pessoal', preco: 36.90, precoOriginal: 46.90, avaliacao: 4.7, avaliacoes: 1834, estoque: 42, paginas: 256, ano: 2017, isbn: '978-8545200765', idioma: 'Português', descricao: 'Uma obra que ensina como transformar ideias em resultados concretos. Paulo Vieira compartilha técnicas e estratégias para superar a procrastinação e agir com foco.', capa: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Autoajuda' },
  { id: 10, titulo: 'O Problema dos Três Corpos', autor: 'Liu Cixin', editora: 'Intrínseca', categoria: 'Ficção', preco: 49.90, precoOriginal: 64.90, avaliacao: 4.8, avaliacoes: 2210, estoque: 27, paginas: 512, ano: 2008, isbn: '978-8551001714', idioma: 'Português', descricao: 'Quando a física moderna começa a colapsar misteriosamente, a cientista Wang Miao embarca em uma investigação que a leva às profundezas de um universo alienígena.', capa: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Ficção Científica' },
  { id: 11, titulo: 'Sapiens', autor: 'Yuval Noah Harari', editora: 'Companhia das Letras', categoria: 'Não Ficção', preco: 56.90, precoOriginal: 74.90, avaliacao: 4.8, avaliacoes: 5320, estoque: 49, paginas: 464, ano: 2015, isbn: '978-8535926828', idioma: 'Português', descricao: 'Uma breve história da humanidade que examina como o Homo sapiens dominou o mundo e moldou a história através da linguagem, mitos e cooperação em grande escala.', capa: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'História' },
  { id: 12, titulo: 'Dom Quixote', autor: 'Miguel de Cervantes', editora: 'Martin Claret', categoria: 'Romance', preco: 35.90, precoOriginal: 44.90, avaliacao: 4.6, avaliacoes: 1243, estoque: 61, paginas: 1024, ano: 1605, isbn: '978-8572329125', idioma: 'Português', descricao: 'Considerado o primeiro romance moderno ocidental, Dom Quixote narra as aventuras do idealista Alonso Quijano, que enlouquece lendo livros de cavalaria.', capa: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=300&h=420&fit=crop', status: 'ATIVO', grupo: 'Clássicos' },
]

export const livroService = {
  listarLivros: async (filtros = {}) => livros_mock.filter(l => {
    if (filtros.categoria && l.categoria !== filtros.categoria) return false
    if (filtros.busca && !l.titulo.toLowerCase().includes(filtros.busca.toLowerCase())) return false
    if (filtros.precoMin && l.preco < filtros.precoMin) return false
    if (filtros.precoMax && l.preco > filtros.precoMax) return false
    return true
  }),
  buscarLivroPorId: async (id) => livros_mock.find(l => l.id === Number(id)),
  criarLivro: async (data) => api.post('/livros', data),
  atualizarLivro: async (id, data) => api.put(`/livros/${id}`, data),
  ativarLivro: async (id) => api.patch(`/livros/${id}/ativar`),
  inativarLivro: async (id) => api.patch(`/livros/${id}/inativar`),
}
