name: Criar PR para Develop

on:
  push:
    branches-ignore:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write


jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar PR para develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base develop \
            --head "${{ github.ref_name }}" \
            --title "Promover ${{ github.ref_name }} para develop" \
            --body "PR criado automaticamente pelo GitHub Actions."